#################################
#             Backend           #
#################################
backend = "glx";
vsync = false;
glx-no-stencil = true;
glx-no-rebind-pixmap = true;
unredir-if-possible = false;
use-damage = true;

#################################
#             Shadows           #
#################################
shadow = true;
shadow-radius = 25;
shadow-opacity = 0.5;
shadow-offset-x = -25;
shadow-offset-y = -25;
shadow-ignore-shaped = true;

shadow-exclude = [
  "window_type = 'dock'",
  "window_type = 'tooltip'",
  "window_type = 'popup_menu' && class_g != ''",
  "window_type = 'dropdown_menu' && class_g != ''",
  "window_type = 'menu' && class_g != ''",
  "_GTK_FRAME_EXTENTS@:c"
];

#################################
#           Corners             #
#################################
corner-radius = 10;

rounded-corners-exclude = [
  "class_g = 'tint2'",
  "window_type = 'popup_menu' && class_g != ''",
  "window_type = 'dropdown_menu' && class_g != ''",
  "window_type = 'menu' && class_g != ''",
  "window_type = 'dock'",
  "window_type = 'tooltip'",
  "window_type = 'utility'",
  "_NET_WM_STATE@:32a *= '_NET_WM_STATE_MAXIMIZED_HELPER'",
  "_NET_WM_STATE@:32a *= '_NET_WM_STATE_MAXIMIZED_VERT'",
  "_NET_WM_STATE@:32a *= '_NET_WM_STATE_MAXIMIZED_HORZ'"
];

#################################
#           Fading              #
#################################
fading = false;

#################################
#           Opacity             #
#################################
inactive-opacity = 1.0;
active-opacity = 1.0;
frame-opacity = 1.0;

#################################
#       General Settings        #
#################################
mark-wmwin-focused = true;
mark-ovlp-focused = true;
detect-rounded-corners = true;
detect-client-opacity = true;
use-damage = true;
log-level = "warn";

wintypes:
{
  popup_menu = { shadow = true; full-shadow = true; }
  dropdown_menu = { shadow = true; full-shadow = true; }
  tooltip = { shadow = false; }
  dock = { shadow = false; }
};
